# Project: bank
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = bank.o bank_a.o bank_b.o
LINKOBJ  = bank.o bank_a.o bank_b.o
LIBS     = -L"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/SSID/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = bank.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

bank.o: bank.cpp
	$(CPP) -c bank.cpp -o bank.o $(CXXFLAGS)

bank_a.o: bank_a.cpp
	$(CPP) -c bank_a.cpp -o bank_a.o $(CXXFLAGS)

bank_b.o: bank_b.cpp
	$(CPP) -c bank_b.cpp -o bank_b.o $(CXXFLAGS)
